const cohesionConfig = {
  name: 'edx',
  slug: 'edx',
  domain: 'edx.org',
  domainLabel: 'edx',
  domainExtension: '.org',
  domainLabelWithExtension: 'edx.org',
  postTypeGql: '',
  homepageGql: '',
  siteUrl: process.env.MARKETING_SITE_BASE_URL,
  cmsUrl: '',
  cmsUser: '',
  cmsPwd: '',
  logoUrl: '',
  studyMatchUrl: '',
  voyagerUrl: '/discover',
  identityToken: '',
  gaCid: '',
  gaSid: '',
  gaMid: '',
  defaultDegree: '',
  defaultCategory: '',
  defaultSubject: '',
  tagularApiKey: '',
  tagularSourceKey: 'src_2euJfAVNt6Z9kQz4e9t1SQBtm8x',
  tagularWriteKey: 'wk_2euJfDkJVTtEVzsC8BPOb0g9dVj',
  tagularCookieDomain: 'edx.org',
  tagularDomainWhitelist: JSON.stringify([
    'edx.org',
  ]),
  monarchSourceId: '',
  monarchToken: '',
  newRelicAppID: '',
  newRelicVoyagerAppID: '',
  cookieLawId: '',
};

module.exports = cohesionConfig;
