const cohesionConfig = {
  name: 'edx',
  slug: 'edx',
  domain: 'edx.org',
  domainLabel: 'edx',
  domainExtension: '.org',
  domainLabelWithExtension: 'edx.org',
  postTypeGql: '',
  homepageGql: '',
  siteUrl: process.env.MARKETING_SITE_BASE_URL,
  cmsUrl: '',
  cmsUser: '',
  cmsPwd: '',
  logoUrl: '',
  studyMatchUrl: '',
  voyagerUrl: '/discover',
  identityToken: '',
  gaCid: '',
  gaSid: '',
  gaMid: '',
  defaultDegree: '',
  defaultCategory: '',
  defaultSubject: '',
  tagularApiKey: '',
  tagularSourceKey: process.env.COHESION_TAGULAR_SOURCE_KEY,
  tagularWriteKey: process.env.COHESION_TAGULAR_WRITE_KEY,
  tagularCookieDomain: 'edx.org',
  tagularDomainWhitelist: JSON.stringify([
    'edx.org',
  ]),
  monarchSourceId: '',
  monarchToken: '',
  newRelicAppID: '',
  newRelicVoyagerAppID: '',
  cookieLawId: '',
};

module.exports = cohesionConfig;
